export const TYPES = {
    BlogRepository: Symbol.for("BlogRepository"),
    BlogService: Symbol.for("BlogService"),
    BlogController: Symbol.for("BlogController"),
    PostRepository: Symbol.for("PostRepository"),
    PostsService: Symbol.for("PostsService"),
    PostsController: Symbol.for("PostsController"),
    CommentRepository: Symbol.for("CommentRepository"),
    CommentLikeStatusRepository: Symbol.for("CommentLikeStatusRepository"),
    CommentsService: Symbol.for("CommentsService"),
    CommentsController: Symbol.for("CommentsController"),
    UserRepository: Symbol.for("UserRepository"),
    UsersService: Symbol.for("UsersService"),
    UsersController: Symbol.for("UsersController"),
    AuthRepository: Symbol.for("AuthRepository"),
    AuthService: Symbol.for("AuthService"),
    AuthController: Symbol.for("AuthController"),
    TokenBlacklistRepository: Symbol.for("TokenBlacklistRepository"),
    TokenBlacklistService: Symbol.for("TokenBlacklistService"),
    RateLimitRepository: Symbol.for("RateLimitRepository"),
    RateLimitService: Symbol.for("RateLimitService"),
    DeviceSessionsRepository: Symbol.for("DeviceSessionsRepository"),
    DeviceSessionsService: Symbol.for("DeviceSessionsService"),
    DeviceSessionsController: Symbol.for("DeviceSessionsController"),
    JwtService: Symbol.for("JwtService"),
    BcryptService: Symbol.for("BcryptService"),
    MailerService: Symbol.for("MailerService"),
    TestingRepository: Symbol.for("TestingRepository"),
    TestingService: Symbol.for("TestingService"),
    TestingController: Symbol.for("TestingController"),
};

export type AppDependency = keyof typeof TYPES;
export type ResolveDependency<T extends AppDependency> = (typeof TYPES)[T];
